language: rust
rust:
- nightly
install:
- rustup target add wasm32-unknown-unknown
- cargo install --git https://github.com/paritytech/wasm-utils --bin wasm-build
script:
- cargo test --features test
- cargo check --target wasm32-unknown-unknown --verbose --features strict
- cargo check --target wasm32-unknown-unknown --verbose --features strict,panic_with_msg
- cargo check --verbose --features strict,std,panic_with_msg
- cd demo && ./build.sh
- cd ..
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc --all --no-deps &&
  echo '<meta http-equiv=refresh content=0;url=pwasm_std/index.html>' > target/doc/index.html &&
  pip install --user ghp-import &&
  /home/travis/.local/bin/ghp-import -n target/doc &&
  git push -fq https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
    secure: v1mjxkYgyCSO4pt7H1BuU3U8EpT7fVI1JJGja0/t45LgoFTUFd5MVY582Z+P2brdHzdjoenPVKfQB64oNrhpF/gRgBWHdprE+3MpUBCVpayecJPEbPycDNas8wFLrEvGhWzOkYP84ShtLuTnk6XlWtXtLYlXel834V/qz0nBmRR7ZvaAQ1dqCgxUDpXzPoM8aYU4PbWhnXB96dubd91wfucUYmiRB6LuzFbUz0qd46Gliz3R574xnx8BPVEb7azpLOrmWspmY8PhRTMdyjFWIGeKLC30O7z69azcMvmfWYeX8OHn2Ctv4o17+FZGTnx6r5sgNBCzWLo9VBB4191g7DRqsVbSMD7z+9LMczEZvVmbwqkAmXQK2zOjcSs1zrP/TmXXpOYvOZXVSele+EdUR9X6G+9Efw98l8Y7pFlWG1OOBEEuh2R5kQ96AOjTcbbbAUEY4bDV54qDaZiFQwjSl1KloL3eKJHWOYmAVqUurVmA7/SMk8bbnlivnWsDdRKm3IymasCtjR2K5rGxDAL6ATJH1kQOj9Jsg060dwHzhe2OYbRR0u3LGLD+XvRsgQZESHqi4SOpMOyx7ywXe2aBbOfuuS6l2g99bdCAU86DXwTpBrwX9y+eqa8JlBwN4t8Ip9lrhev8thFZz5FLDXhfU9wGZnuTKymEAGzoeySWurw=
