language: rust

rust:
  - nightly
sudo: required
services:
  - docker
before_install:
  - docker run -dit --name emscripten -v $(pwd):/src alexfro/rust-wasm32-unknown-emscripten bash
script:
  - cargo build --features strict,std
  - cargo build --verbose --features strict --manifest-path=alloc/Cargo.toml
  - cargo build --verbose --features strict --manifest-path=libc/Cargo.toml
  - cargo check --verbose --features strict
  - cargo check --verbose --features strict,panic_with_msg
  - cargo check --verbose --features strict,std,panic_with_msg
  - docker exec -it emscripten sh -c "cargo install --git https://github.com/paritytech/wasm-utils wasm-build"
  - docker exec -it emscripten sh -c "cd demo && ./build.sh"
