language: rust
rust:
- nightly
install:
- rustup target add wasm32-unknown-unknown
- cargo install --git https://github.com/paritytech/wasm-utils --bin wasm-build
script:
- cargo test --features test
- cargo check --target wasm32-unknown-unknown --verbose --features strict
- cargo check --target wasm32-unknown-unknown --verbose --features strict,panic_with_msg
- cargo check --verbose --features strict,std,panic_with_msg
- cd demo && ./build.sh
- cd ..
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc --all --no-deps &&
  echo '<meta http-equiv=refresh content=0;url=pwasm_std/index.html>' > target/doc/index.html &&
  pip install --user ghp-import &&
  /home/travis/.local/bin/ghp-import -n target/doc &&
  git push -fq https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
  - secure: sR7zsC7POowXa2DT4BHx7ReQZBUdH+2IZQIMtgTYfln2IawiXZCAV1mXiG4WgZVvSNjO3+a5kBa59WRkDy6/iQOtY0MTFiaQsfFXWUKdC6ISngGZIiqPQbBV2E0J3vmZRE99W3tZrx6C8aQwToh+IfrX/ISJ0kKUM/pIirxfkykb3enOhNO3k5jnRPO+4uiaMhEnjHMhPCRPO6mjQ9Lkwe9WswVmEvhS26ivUP0ZgP5qURqrAtH5pyHBLshIVyXSCQj+PYaBdt1zTeHOvO0Kdq5xZrvhk8f/r2fW2d7lw5G9p1qnI6p58BMnlHIaoBD8TZt/tyTkO4vcwPhWUKMMmR0F7RQWbtI5lIFgWVybaojgVA9s7umP5SNesAJpxkGfgoFwiMwWVjYC+OzUsMsl7jyNsgGbkt4zSuCEJqatemFPPeVtvucPxsAYHv42cHlK6UWo91EfPqoffmQx/DHVgQ+50j8VWzNz88QjXahVKq5FQCs+fIvtSKDr3Y8WYACW+n4aU7XiVdjDjvDcJzmnDl1GmIe1K2nkXGr55YKmoX2slf+Uky9tDk2bJNTL8mFAKMC2JWS372v/SkHI5XjX+WMt8N8q1p1nCnjnFTRUO4PnNxnjygsECjpE8/ez7PjNuG0ZnQzoRFrtR8C7idzSEvODOK1veNzeZcStvpmuAbg=
