language: rust
rust:
  - nightly
sudo: required
services:
  - docker
before_install:
  - docker run -dit --name emscripten -v $(pwd)/demo:/source jasonuhl/rust-wasm bash
script:
  - docker exec -it emscripten ./build.sh
  - cargo build --verbose --all
