[package]
name = "pwasm-std"
version = "0.1.0"
authors = ["NikVolf <nikvolf@gmail.com>"]

[dependencies]
wasm-alloc = { path = "alloc" }
wasm-libc = { path = "libc" }
tiny-keccak = "1.3"
cfg-if = "0.1"

[dependencies.bigint]
version = "4"
default-features = false

[dependencies.byteorder]
version = "1"
default-features = false

[dependencies.parity-hash]
version = "1"
default-features = false

[features]
default = []
std = ["parity-hash/std", "bigint/std"]
strict = []
panic_with_msg = []
