[package]
name = "wasm-std-demo"
version = "0.0.0"
authors = ["NikVolf <nikvolf@gmail.com>"]
target-dir = "wasm"

[dependencies]
pwasm-std = { path = "../" }

[[bin]]
name = "wasm-demo"
path = "src/main.rs"

[profile.release]
panic = "abort"
